const CONST = {
    ADD_TODO: "ADD_TODO",
    TOGGLE_TODO: "TOGGLE_TODO",
    SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
    RECEIVEDATA: "RECEIVEDATA",
    REQUESTDATA: "REQUESTDATA",
    FILTERS: {
        SHOW_ALL: "SHOW_ALL",
        SHOW_UNFINISHED: "SHOW_UNFINISHED",
        SHOW_FINISHED: "SHOW_FINISHED"
    }
};
export default CONST;